spring:
  application:
    name: expense-tracker
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

app:
  expenses:
    undo-delete-window: PT5M

springdoc:
  api-docs:
    path: /v3/api-docs
